# Generated by Django 6.1 on 2026-08-31 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo_produto', models.CharField(choices=[('LIVRO', 'Livro'), ('LP', 'LP'), ('CD', 'CD'), ('DVD', 'DVD')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='produtos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('numero_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('ano_publicacao', models.PositiveIntegerField(blank=True, null=True)),
                ('edicao', models.CharField(blank=True, max_length=50, null=True)),
                ('idioma', models.CharField(blank=True, max_length=50, null=True)),
                ('peso_gramas', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=50, null=True)),
                ('altura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('largura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('espessura_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('autores', models.ManyToManyField(related_name='livros', to='produtos.autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livros', to='produtos.editora')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livro', to='produtos.produto')),
            ],
        ),
    ]
